version: "3.9"  # optional since v1.27.0
services:
  api:
    container_name: webapi
    image: mcr.microsoft.com/dotnet/aspnet:5.0
    build:
      context: ./
    depends_on:
      - db
    ports:
      - "8080:80"
  db:
    container_name: apidb
    image: mysql:latest
    restart: always
    build:
      context: ./database
    environment:
      MYSQL_ROOT_PASSWORD: test
    ports:
      - "3306:3306"
    volumes:
      - ./mygram:/var/lib/mysql

volumes:
  mygram:


