version: "3.9"  # optional since v1.27.0
services:
  api:
    container_name: webapi
    image: mcr.microsoft.com/dotnet/aspnet:5.0
    build:
      context: ./
    depends_on:
      - db
    ports:
      - "8080:80"
  db:
    container_name: apidb
    command: --default-authentiation-plugin=mysql_native-password
    build:
      context: ./database
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    ports:
      - "3306:3306"

